AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploy OpenSearch domain in private subnet with minimal configuration"

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: vpc-03b6500a08507f107
    Description: VPC for the OpenSearch domain
  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Default: "subnet-05294552d2978db95,subnet-01755fd9859ba9c5e"
    Description: List of private subnets for the OpenSearch domain (minimum 2 for zone awareness)
  ProxyServerCidrRange:
    Type: String
    Default: "152.0.0.0/16"
    Description: CIDR range of the proxy server subnet or VPC
  DomainName:
    Type: String
    Default: my-demo
    Description: Name for the OpenSearch domain
    AllowedPattern: "[a-z][a-z0-9\\-]+"
    ConstraintDescription: Domain name must start with a lowercase letter and contain only lowercase letters, numbers, and hyphens
  EnableFineGrainedAccess:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    Description: Enable fine-grained access control

Conditions:
  EnableFGAC: !Equals [!Ref EnableFineGrainedAccess, "true"]

Resources:
  # Secrets Manager secret for master user credentials
  MasterUserSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${DomainName}-master-user-secret"
      Description: !Sub "Master user credentials for OpenSearch domain ${DomainName}"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        RequireEachIncludedType: true
        ExcludeCharacters: '"@/\\'
      Tags:
        - Key: Name
          Value: !Sub "${DomainName}-master-user-secret"
        - Key: Domain
          Value: !Ref DomainName

  OpenSearchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: OpenSearch private access
      GroupName: opensearch-private
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref ProxyServerCidrRange
          Description: HTTPS access from proxy server CIDR range
      Tags:
        - Key: Name
          Value: opensearch-private

  OpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: !Ref DomainName
      EngineVersion: OpenSearch_2.11
      ClusterConfig:
        DedicatedMasterEnabled: false
        InstanceCount: 2
        InstanceType: m6g.large.search
        ZoneAwarenessEnabled: true
        ZoneAwarenessConfig:
          AvailabilityZoneCount: 2
      EBSOptions:
        EBSEnabled: true
        VolumeType: gp3
        VolumeSize: 20
      VPCOptions:
        SubnetIds: !Ref PrivateSubnetIds
        SecurityGroupIds:
          - !Ref OpenSearchSecurityGroup
      DomainEndpointOptions:
        EnforceHTTPS: true
        TLSSecurityPolicy: Policy-Min-TLS-1-2-2019-07
      EncryptionAtRestOptions:
        Enabled: true
      NodeToNodeEncryptionOptions:
        Enabled: true
      AdvancedSecurityOptions:
        Enabled: !If [EnableFGAC, true, false]
        InternalUserDatabaseEnabled: !If [EnableFGAC, true, false]
        MasterUserOptions: !If
          - EnableFGAC
          - MasterUserName: !Sub '{{resolve:secretsmanager:${MasterUserSecret}:SecretString:username}}'
            MasterUserPassword: !Sub '{{resolve:secretsmanager:${MasterUserSecret}:SecretString:password}}'
          - !Ref AWS::NoValue
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: "es:*"
            Resource: !Sub "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${DomainName}/*"
      AdvancedOptions:
        "rest.action.multi.allow_explicit_index": "true"
        "indices.fielddata.cache.size": "20"
        "indices.query.bool.max_clause_count": "1024"
      Tags:
        - Key: Name
          Value: !Ref DomainName

Outputs:
  OpenSearchDomainEndpoint:
    Description: OpenSearch domain VPC endpoint
    Value: !GetAtt OpenSearchDomain.DomainEndpoint
  OpenSearchDashboardsURL:
    Description: OpenSearch Dashboards URL
    Value: !Sub "https://${OpenSearchDomain.DomainEndpoint}/_dashboards/"
  OpenSearchSecurityGroupId:
    Description: Security Group ID for OpenSearch
    Value: !Ref OpenSearchSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-OpenSearchSecurityGroup"
  MasterUserSecretArn:
    Description: ARN of the Secrets Manager secret containing master user credentials
    Value: !Ref MasterUserSecret
    Export:
      Name: !Sub "${AWS::StackName}-MasterUserSecret"
